name: Deploy Blog
  
# run on every commit on the master branch
on:
  push:
    branches:
      - master
      - github-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo and the theme
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
      - name: Run Hugo
        run: hugo --minify
      - name: Download s3deploy
        run: wget https://github.com/bep/s3deploy/releases/download/v2.2.0/s3deploy_2.2.0_Linux-64bit.deb
      - name: Install s3deploy
        run: sudo dpkg -i s3deploy*.deb
      - name: Run s3deploy
        run: s3deploy -source=public/ -region=us-east-1 -bucket=parsiya.net -distribution-id E3S0DM3VADRBW7 -key ${{ secrets.ID }} -secret ${{ secrets.KEY }}

