name: Deploy Blog
  
# run on every commit on the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: git submodule update --init --recursive # clone the theme repo
      # download and install Hugo
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
      - run: sudo dpkg -i hugo*.deb
      # download and install s3deploy
      - run: wget https://github.com/bep/s3deploy/releases/download/v2.2.0/s3deploy_2.2.0_Linux-64bit.deb
      - run: sudo dpkg -i s3deploy*.deb
      # run hugo
      - run: hugo --minify
      # run s3deploy
      - run: s3deploy -source=public/ -region=us-east-1 -bucket=parsiya.net -distribution-id E3S0DM3VADRBW7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY }}
